# Ye change zaroori hai
server.port=${PORT:8081}
#server.address=127.0.0.1
#server.address=192.168.0.106
# server.address hata do (Render ise handle karega)
#server.address=192.168.1.220
# Baki aapka scheduler setup sahi hai
spring.task.scheduling.pool.size=2
spring.task.scheduling.thread-name-prefix=chat-cleanup-

# Memory bachane ke liye ye do lines add kar lo
spring.main.lazy-initialization=true
server.tomcat.threads.max=10


# WebSocket message size
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Tomcat buffer size
server.tomcat.max-http-form-post-size=10MB
server.tomcat.max-swallow-size=10MB

logging.level.com.alibou.websocket.config.ChatCleanupScheduler=INFO