server.port=5672
server.address=192.168.1.220
# Scheduler Configuration
spring.task.scheduling.pool.size=2
spring.task.scheduling.thread-name-prefix=chat-cleanup-

# Logging level for scheduler (optional)
logging.level.com.alibou.websocket.config.ChatCleanupScheduler=INFO